### ISSUE TITLE
Fix Fort bug - Game freezes after fort is destroyed.

### ISSUE THREAD

**Issue by camfritz** [joshuajmurray/InvadersRevenge#46]

**Comment by joshuajmurray** [comment]
java.lang.NullPointerException
	at edu.osucascades.cs361.chi.Fort.kill(Fort.java:29)
	at edu.osucascades.cs361.chi.Game.checkForCollisions(Game.java:56)
	at edu.osucascades.cs361.chi.Game.draw(Game.java:38)
	at edu.osucascades.cs361.chi.Sketch.draw(Sketch.java:19)
	at processing.core.PApplet.handleDraw(PApplet.java:2437)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1557)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)
